FrontBrainSight/appBS/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("select/", views.home, name="home"),
    path("resultado/", views.informacion, name="resultado")
]

FrontBrainSight/authentication/urls.py
from django.urls import path
from authentication.views import (
    
    auth_login_view,
    auth_register_view,
    auth_recover_password_view,
    auth_lock_screen_view,
    
)

app_name = 'authentication'

urlpatterns = [
    
    path('login',view=auth_login_view,name='login'),
    path('register',view=auth_register_view,name='register'),
    path('recover_password',view=auth_recover_password_view,name='recover_password'),
    path('lock_screen',view=auth_lock_screen_view,name='lock_screen'),
    
    
    
]

FrontBrainSight/brainSight/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from brainSight import views
from django.contrib.auth.decorators import login_required
from .views import MyPasswordChangeView, MyPasswordSetView


urlpatterns = [
    
    path('admin/', admin.site.urls),
    
    # Index
    path('index',views.index,name="index"),
    
    # App
    path ("prueba/", include("appBS.urls")),
    
    # dashboard
    path("",include('dashboard.urls')),
    
    # e_mail
    path('e_mail/',include('e_mail.urls')),
    
    # authentication
    path('authentication/',include('authentication.urls')),
    
    # pages
    path('pages/',include('pages.urls')),
    
    # components
    path('components/',include('components.urls')),
    
    path(
        "account/password/change/",
        login_required(MyPasswordChangeView.as_view()),
        name="account_change_password",
    ),
    path(
        "account/password/set/",
        login_required(MyPasswordSetView.as_view()),
        name="account_set_password",
    ),
    
    # All Auth 
    path('account/', include('allauth.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FrontBrainSight/dashboard/urls.py
from django.urls import path
from dashboard.views import (
    
    dashboard_view,
    calendar_view,
)

app_name = 'dashboard'

urlpatterns = [
    
    path('',view=dashboard_view,name='dashboard'),
    path('calendar',view=calendar_view,name='calendar'),
    
]

FrontBrainSight/e_mail/urls.py
from django.urls import path
from e_mail.views import (
    
    email_inbox,
    email_read,
    email_compose,
    
)

app_name="e_mail"

urlpatterns = [
    
    path('inbox',view=email_inbox,name='inbox'),
    path('read',view=email_read,name='read'),
    path('compose',view=email_compose,name='compose'),
    
]

FrontBrainSight/pages/urls.py
from django.urls import path
from pages.views import (
    
    pages_starter,
    pages_maintenance,
    pages_coming_soon,
    pages_timeline,
    pages_gallery,
    pages_faqs,
    pages_pricing,
    pages_error404,
    pages_error500,
    
)

app_name = 'pages'

urlpatterns = [
    
    path('starter',view=pages_starter,name='starter'),
    path('maintenance',view=pages_maintenance,name='maintenance'),
    path('coming_soon',view=pages_coming_soon,name='coming_soon'),
    path('timeline',view=pages_timeline,name='timeline'),
    path('gallery',view=pages_gallery,name='gallery'),
    path('faqs',view=pages_faqs,name='faqs'),
    path('pricing',view=pages_pricing,name='pricing'),
    path('error404',view=pages_error404,name='error404'),
    path('error500',view=pages_error500,name='error500'),
    
]

FrontBrainSight/templates/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <title>{% block title %} {% endblock title %} | Xoric - Responsive Bootstrap 5 Admin Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Themesdesign" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

        {% block css %}
        {% block extra_css %}
        {% endblock extra_css %}

        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css" /> 

        {% endblock css %}

    </head>

    {% block body %}
        <body data-topbar="colored">    
    {% endblock body %}

    <!-- Begin page -->
    <div id="layout-wrapper">

        {% comment %} {% block horizontal %}
            {% include "partials/horizontal.html" %}
        {% endblock horizontal %}   {% endcomment %}

        {% block topbar %}
            {% include "partials/topbar.html" %}
        {% endblock topbar %}

       {% block sidebar %}
            {% include "partials/sidebar.html" %}
        {% endblock sidebar %}  

        <div class="main-content">
            <div class="page-content">

                {% block pagetitle %}
                {% endblock pagetitle %}

                <div class="page-content-wrapper">
                    <div class="container-fluid">

                        {% block content %}

                        {% endblock content %}


                    </div> <!-- container-fluid -->
                </div>
                <!-- end page-content-wrapper -->
            </div>
            <!-- End Page-content -->

            
            {% block footer %}
            {% include "partials/footer.html" %}
            {% endblock footer %}


        </div>
        <!-- end main content-->

    </div>
    <!-- END layout-wrapper -->

      
    {% block right_sidebar %}
    {% include "partials/right-sidebar.html" %}
    {% endblock right_sidebar %}

    {% block javascript %}

        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'libs/metismenu/dist/metisMenu.min.js' %}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
        <script src="{% static 'libs/node-waves/dist/waves.min.js' %}"></script>

        <script src="https://unicons.iconscout.com/release/v2.0.1/script/monochrome/bundle.js"></script>        

        {% block extra_js %}
        {% endblock extra_js %}

        <script src="{% static 'js/app.js' %}"></script>
    
    {% endblock javascript %}

</body>
</html>

FrontBrainSight/templates/partials/footer.html
{% block footer %}

<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
            <script>document.write(new Date().getFullYear())</script> © Xoric.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                    Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesdesign
                </div>
            </div>
        </div>
    </div>
</footer>

{% endblock footer %}

FrontBrainSight/templates/partials/page-title.html
{% block pagetitle %}
<!-- Page-Title -->
<div class="page-title-box">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h4 class="page-title mb-1">{{title}}</h4>
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">{{pagetitle}}</a></li>
                <li class="breadcrumb-item active">{{title}}</li>
                </ol>
            </div>
            <div class="col-md-4">
                <div class="float-end d-none d-md-block">
                    <div class="dropdown d-inline-block">
                        <button type="button" class="btn btn-light rounded-pill user text-start d-flex align-items-center" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-settings-outline me-1"></i> Settings
                        </button>
                        <div class="dropdown-menu dropdown-menu-end">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- end page title end breadcrumb -->

{% endblock pagetitle %}

FrontBrainSight/templates/partials/sidebar.html
{% load static %}
{% block sidebar %}

<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">Menu</li>

                <li>
                    <a href="{% url 'dashboard:dashboard' %}" class="waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-airplay"></i></div><span class="badge rounded-pill text-bg-success float-end">3</span>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'dashboard:calendar' %}" class=" waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-schedule"></i></div>
                        <span>Calendar</span>
                    </a>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-comment-message"></i></div>
                        <span>Email</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'e_mail:inbox' %}">Inbox</a></li>
                        <li><a href="{% url 'e_mail:read' %}">Email Read</a></li>
                        <li><a href="{% url 'e_mail:compose' %}">Email Compose</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-sign-in-alt"></i></div>
                        
                        <span>Authentication</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'authentication:login' %}">Login</a></li>
                        <li><a href="{% url 'authentication:register' %}">Register</a></li>
                        <li><a href="{% url 'authentication:recover_password' %}">Recover Password</a></li>
                        <li><a href="{% url 'authentication:lock_screen' %}">Lock Screen</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-grids"></i></div>
                        <span>Pages</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'pages:starter' %}">Starter Page</a></li>
                        <li><a href="{% url 'pages:maintenance' %}">Maintenance</a></li>
                        <li><a href="{% url 'pages:coming_soon' %}">Coming Soon</a></li>
                        <li><a href="{% url 'pages:timeline' %}">Timeline</a></li>
                        <li><a href="{% url 'pages:gallery' %}">Gallery</a></li>
                        <li><a href="{% url 'pages:faqs' %}">FAQs</a></li>
                        <li><a href="{% url 'pages:pricing' %}">Pricing</a></li>
                        <li><a href="{% url 'pages:error404' %}">Error 404</a></li>
                        <li><a href="{% url 'pages:error500' %}">Error 500</a></li>
                    </ul>
                </li>

                <li class="menu-title">Components</li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-box"></i></div>
                        <span>Bootstrap UI</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'components:bootstrap-ui.alerts' %}">Alerts</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.badges' %}">Badge</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.buttons' %}">Buttons</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.cards' %}">Cards</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.dropdowns' %}">Dropdowns</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.navs' %}">Navs</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.tabs_accordions' %}">Tabs &amp; Accordions</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.modals' %}">Modals</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.images' %}">Images</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.progressbars' %}">Progress Bars</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.pagination' %}">Pagination</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.popover_tooltips' %}">Popover & Tooltips</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.spinner' %}">Spinner</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.carousel' %}">Carousel</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.video' %}">Video</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.typography' %}">Typography</a></li>
                        <li><a href="{% url 'components:bootstrap-ui.grid' %}">Grid</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-layer-group"></i></div>
                        <span>Advanced UI</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'components:advance-ui.alertify' %}">Alertify</a></li>
                        <li><a href="{% url 'components:advance-ui.ratings' %}">Rating</a></li>
                        <li><a href="{% url 'components:advance-ui.nestable' %}">Nestable</a></li>
                        <li><a href="{% url 'components:advance-ui.rangeslider' %}">Range Slider</a></li>
                        <li><a href="{% url 'components:advance-ui.sweet_alert' %}">Sweet-Alert</a></li>
                        <li><a href="{% url 'components:advance-ui.lightbox' %}">Lightbox</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-object-ungroup"></i></div>
                        <span>Icons</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'components:icons.materialdesign' %}">Material Design</a></li>
                        <li><a href="{% url 'components:icons.dripicons' %}">Dripicons</a></li>
                        <li><a href="{% url 'components:icons.fontawesome' %}">Font Awesome 5</a></li>
                        <li><a href="{% url 'components:icons.themify' %}">Themify</a></li>
                        <li><a href="{% url 'components:icons.unicons' %}">Unicons - Dual Tone</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-table"></i></div>
                        <span>Tables</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'components:tables.basic' %}">Basic Tables</a></li>
                        <li><a href="{% url 'components:tables.datatable' %}">Data Tables</a></li>
                        <li><a href="{% url 'components:tables.responsive' %}">Responsive Table</a></li>
                        <li><a href="{% url 'components:tables.editable' %}">Editable Table</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);" class="waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-document-layout-left"></i></div>
                        <span class="badge rounded-pill text-bg-danger float-end">07</span>
                        <span>Forms</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'components:forms.elements' %}">Form Elements</a></li>
                        <li><a href="{% url 'components:forms.validation' %}">Form Validation</a></li>
                        <li><a href="{% url 'components:forms.advanced' %}">Form Advanced</a></li>
                        <li><a href="{% url 'components:forms.editors' %}">Form Editors</a></li>
                        <li><a href="{% url 'components:forms.file_uploads' %}">Form File Upload</a></li>
                        <li><a href="{% url 'components:forms.mask' %}">Form Mask</a></li>
                        <li><a href="{% url 'components:forms.summernote' %}">Summernote</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-chart-pie"></i></div>
                        <span>Charts</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'components:charts.morris' %}">Morris</a></li>
                        <li><a href="{% url 'components:charts.apex' %}">Apex</a></li>
                        <li><a href="{% url 'components:charts.chartist' %}">Chartist</a></li>
                        <li><a href="{% url 'components:charts.chartjs' %}">Chartjs</a></li>
                        <li><a href="{% url 'components:charts.flot' %}">Flot</a></li>
                        <li><a href="{% url 'components:charts.sparkline' %}">Sparkline</a></li>
                        <li><a href="{% url 'components:charts.knob' %}">Jquery Knob</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-comment-plus"></i></div>
                        <span>Maps</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'components:maps.google' %}">Google map</a></li>
                        <li><a href="{% url 'components:maps.vector' %}">Vector map</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-window-grid"></i></div>
                        <span>Layouts</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'components:layouts.horizontal' %}">Horizontal</a></li>
                        <li><a href="{% url 'components:layouts.dark_sidebar' %}">Dark Sidebar</a></li>
                        <li><a href="{% url 'components:layouts.small_sidebar' %}">Small Sidebar</a></li>
                        <li><a href="{% url 'components:layouts.icon_sidebar' %}">Icon Sidebar</a></li>
                        <li><a href="{% url 'components:layouts.colored_sidebar' %}">Colored Sidebar</a></li>
                        <li><a href="{% url 'components:layouts.boxed_sidebar' %}">Boxed Layout</a></li>
                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <div class="d-inline-block icons-sm me-1"><i class="uim uim-layers-alt"></i></div>
                        <span>Multi Level</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="true">
                        <li><a href="javascript: void(0);">Level 1.1</a></li>
                        <li><a href="javascript: void(0);" class="has-arrow">Level 1.2</a>
                            <ul class="sub-menu" aria-expanded="true">
                                <li><a href="javascript: void(0);">Level 2.1</a></li>
                                <li><a href="javascript: void(0);">Level 2.2</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>

            </ul>

        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->

{% endblock sidebar %}

FrontBrainSight/templates/partials/topbar.html
{% load static %}
{% block topbar %}

<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="{% url 'dashboard:dashboard' %}" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-sm-dark.png' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-dark.png' %}" alt="" height="20">
                    </span>
                </a>

                <a href="{% url 'dashboard:dashboard' %}" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-sm-light.png' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-light.png' %}" alt="" height="20">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-24 header-item waves-effect" id="vertical-menu-btn">
                <i class="mdi mdi-backburger"></i>
            </button>

            <!-- App Search-->
            <form class="app-search d-none d-lg-block">
                <div class="position-relative mt-3">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="mdi mdi-magnify"></span>
                </div>
            </form>
        </div>

        <div class="d-flex">

            <div class="dropdown d-inline-block d-lg-none ms-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-magnify"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0" aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="form-group mt-3">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="dropdown d-inline-block language-switch">
                <button type="button" class="btn header-item noti-icon" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img id="header-lang-img" src="{% static 'images/flags/us.jpg' %}" alt="Header Language" height="14">
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="sp">
                        <img src="{% static 'images/flags/spain.jpg' %}" alt="user-image" class="me-2" height="12"> <span class="align-middle">Spanish</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="gr">
                        <img src="{% static 'images/flags/germany.jpg' %}" alt="user-image" class="me-2" height="12"> <span class="align-middle">German</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="it">
                        <img src="{% static 'images/flags/italy.jpg' %}" alt="user-image" class="me-2" height="12"> <span class="align-middle">Italian</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="ru">
                        <img src="{% static 'images/flags/russia.jpg' %}" alt="user-image" class="me-2" height="12"> <span class="align-middle">Russian</span>
                    </a>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon right-bar-toggle waves-effect">
                    <i class="mdi mdi-tune"></i>
                </button>
            </div>

            <!-- light dark btn -->
            <div class="dropdown d-none d-sm-inline-block">
                <button type="button" class="btn header-item" id="light-dark-mode">
                    <i class="mdi mdi-moon-waning-crescent align-middle fs-4"></i>
                </button>
            </div>

            

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item user text-start d-flex align-items-center" id="page-header-user-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="{% static 'images/users/avatar-1.jpg' %}" alt="Header Avatar">
                    <span class="d-none d-sm-inline-block ms-1">{{user.username}}</span>
                    <i class="mdi mdi-chevron-down d-none d-sm-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end ">
                    <a class="dropdown-item" href="#"><i class="mdi mdi-face-profile font-size-16 align-middle me-1"></i> Profile</a>
                    <a class="dropdown-item" href="#"><i class="mdi mdi-credit-card-outline font-size-16 align-middle me-1"></i> Billing</a>
                    <a class="dropdown-item" href="#"><i class="mdi mdi-account-settings font-size-16 align-middle me-1"></i> Settings</a>
                    <a class="dropdown-item" href="#"><i class="mdi mdi-lock font-size-16 align-middle me-1"></i> Lock screen</a>
                    <div class="dropdown-divider"></div>

                {% if user.is_authenticated %}
                    {% if user.has_usable_password %}
                    
                        <a class="dropdown-item" href="{% url 'account_change_password' %}">
                            <i class="mdi mdi-key font-size-16 align-middle me-1"></i>Change Password</a>

                        <a class="dropdown-item" href="{% url 'account_logout' %}">
                            <i class="mdi mdi-logout font-size-16 align-middle me-1"></i>Logout</a>
                    {% endif %}
                {% else %}
                    <a class="dropdown-item" href="{% url 'account_login' %}">
                        <i class="mdi mdi-login font-size-16 align-middle me-1"></i>Log in</a>

                {% endif %}
                </div>
            </div>


        </div>
    </div>

</header>

{% endblock topbar %}